[gcp_service_account]
type = "service_account"
project_id = "custom-woodland-392216"
private_key_id = "3480bc386d7c5b6305271b994cfa804f7d0c6da8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnGwp2Dp4RhDoN
xZklTdGOnvwC8MPZ6e4aNXPqNmqUIhfflf0bR0X0eqzu/fZAQjcgvLBf3HdJnlUS
hG0iP6cdDavuSNNhxqknjhPspli4OxkuXc2Y4zC8cpfinTG0/JwHc6/ZE3PKJwna
znOvyVaHILmZcM1gswudMIPFi2UWLxx/9leK1+M+9fdPnT+QN7zrYyMxSd+6OQch
l0BgFOl3sCKUk8j7Bns9plP0erlY9swsBMH6iJsQ5mk4E+n5R/27MRpw6YXqg4sj
in7CluKVjIO7qb53qEnBpeLMs2QXN2dnpqbgpFvd/2eoL63fXh7byrPi/AuVMJ3r
/cdMSOrlAgMBAAECggEAGR1jjFxEjgHnPsAitPxV4T9MRX3dlaAGuNotRndwu7xH
BcPTY1jqLuUMHiw9qSk6g1lQkcu/AunAw/RyuYnDCkcOftTjriePL0J3hKL4pRG+
xlzzREXrAnufj7/L43Vu1uDgfjnh9nE5FjFeqj4SmuMEegb92wl11qVevJ8nbXaf
ft97fFtNX/Re5ZAl6klKuM4+zfKKwC7Bllq2SEeyg+/Jnfq9gakRwFM0Wxg5rGH0
xfQVhCuGReSF9aWZYOxCLIKr3aXDduKJcGoqJS19yk/Igi5fnDpJZeQF1/X8NVni
1cFfF0kwTUInX8N47LP2QqXqFKHdOUAyK8tl3ejDSQKBgQDRnG8beRhhzbymBUs8
CL+v9lb8KXllRHVIi806ReFQYs6rvh2cme81furff3JUzPkocOodGCJ6YKVtsSZ9
RWvhkRXVMpjygIk1XbzuWJnxr2AajQ10D0/RuXSc1pE3QYK3QwuuCIOYDlc9N6kE
3asx8w6zR7tVSnGJpX2djqXFiQKBgQDMFnNjWF0AiSKhtpHVg8KKCLQh+71A06Rk
lWeOJLPGhcGQ4uOHXjyJ426W+/kwFrSLMRJ73WANy6jdKmz6lzb2vNcHdKhUcreW
6aJ7uSHQ3Uu6RFJ4VIfOrFm/VmnM8nLoYf1Uo31s3id9ZZuE6GMaYGwxTGfP4hWw
J1lmh/T/fQKBgQDHZT+Qa96U00i8ydZq0ou+kODoWW/AtKG5FDxzTZxrgsLFP0Ie
AZU7V3OIjk0tfBscrGUYrifGMH/N3DIYAt0AI6sYN1ylez6KxJQAS8qNzV3ng/yj
RhmRERFsTPSxEqGNQbsvn6vHDwVQF82x8khzaJq4UulS1lExNntLUTJCuQKBgQCz
k6WgaqYazI/+fyi/GRraXmIx7NJP8moaXyQpfL37FsKFfD78Y70dD1PF4p0W5UOj
nmBHQTk9qlBBmw0dSmUAopUKaGmdNPu5/IYOG45XvADgOzHd03NUNW8a3yxlO4hE
VcSU7u50Ft3khr1bKyfYk7NfhX1q++Jdh6Iwh7zZ+QKBgAmsHOxH0lFgYXORzdNE
elptykhqnOpa7DjH8PB0K7xT+jep+pJx3lPZRC6jcXFpAA7s6+cu0vvOCP5eRQDt
CLjcntjEIkzCAQqScT2atrCSOuDsuwmte4S1aJuvHBTDIXdxcT8Mxr7M7OFwiWuC
tQhDvnlUCDlmtx7FlXZMwwJH
-----END PRIVATE KEY-----"""
client_email = "planilhabase@custom-woodland-392216.iam.gserviceaccount.com"
client_id = "117229604540676166864"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/planilhabase%40custom-woodland-392216.iam.gserviceaccount.com"
universe_domain = "googleapis.com"